# safelist
branches:
  only:
  - master
  - develop

os:
  - linux

language: python
python:
  - "2.7"

env:
  - LIBREGF-PYTHON-VERSION=20141030
  - LIBREGF-PYTHON-VERSION=20160424

install:
 - wget https://github.com/libyal/libregf/releases/download/$LIBREGF-PYTHON-VERSION/libregf-alpha-$LIBREGF-PYTHON-VERSION.tar.gz
 - tar xzvf libregf-alpha-$LIBREGF-PYTHON-VERSION.tar.gz
 - pushd libregf-$LIBREGF-PYTHON-VERSION && ./configure --enable-python && make && sudo make install && python setup.py build && python setup.py install && popd
 - pip install faker
 - pip install -r requirements.txt --use-mirrors

# command to run tests
script: pytest ./test/test_status.py ./test/test_dump.py ./test/test_filehitcount.py ./test/test_leven.py ./test/test_mpengine.py ./test/test_search.py ./test/test_stack.py ./test/test_tcorr.py ./test/test_tstack.py ./test/test_tstomp.py


notifications:
  email:
    on_success: never
    on_failure: always